### ISSUE TITLE
CRC32 implementation

### ISSUE THREAD

**Issue by itwysgsl** [bschn2/rainforest#16] opened 2019-04-07 16:19 UTC
Today developer of WildRig (amd miner for rainforest) shared [this](https://create.stephan-brumme.com/crc32/) link in our discord. I beleive that this implementation of crc32 based on lookup tables. @bschn2 maybe you shoud take a look on it.

**Comment by wtarreau** [comment] 2019-04-07 17:06
I can respond on this one as it's one of the sites I had consulted to implement CRC32 in my SLZ compression library ( http://www.libslz.org/ ). Yes, CRC32 is best implemented using lookup tables when you have nothing dedicated instruction. You can use various lookup sizes, but the most common are one byte at a time (1kB table and 4kB table for the parallel lookup). It's also possible to lookup 2 bytes at a time but it requires 256kB and will thrash the cache. There also exists an implementation based on SSE/AVX which apparently is not faster than the table on small blocks due to the high setup cost. With the table, when it fits in L1 cache it's possible to waste only very few cycles per byte.

In libslz we use a variant of the "slice by 4" algo in the link above (ours uses inverted values as it's more convenient this way when compressing), it's roughly 4 cycles per input byte. From what I'm seeing, the rainforest code uses the 8-bit at once version. My testing in the past showed that the differences were only visible when processing large blocks. In rainforest it's only used with 32-bit blocks so we can expect to roughly turn x+4x4 cycles into y+4x3 cycles using 4 times more memory. It could be measured but given that it will significantly impact the L1 cache footprint to save at best 4 cycles per call, I'm not convinced it's worth it as these 4 cycles are less than the cost of an L1 miss caused by this larger footprint. The difference in libslz was already not huge on 16kB blocks.

It can be worth trying anyway if someone wants to give it a try.

**Comment by bschn2** [comment] 2019-04-28 16:05
Let's close this one, it is still readable by filtering on closed anyway.

**Closed as completed by bschn2** 2019-04-28 16:05 UTC
